### ISSUE TITLE
AI issues in 3652

### ISSUE THREAD

**Issue by Nojoke185** [FAForever/fa#1165]
Using latest 3652 code, when playing skirmish or lan game with AI getting below errors:

side effects seen:

1 - No units shoot at each other (enemies)
2 - It is possible to see buildings being constructed through fog of war

To recreate, load latest 3652 from github and run a skirmish or lan game vs 3 AI at Blasted rock map
(No mods were in use)

WARNING: Error running lua script: ...faforever\bin\fa-release-3652\lua\ai\aiutilities.lua(558): attempt to call method `GetArmyStartPos' (a nil value)
         stack traceback:
         	...faforever\bin\fa-release-3652\lua\ai\aiutilities.lua(558): in function `AIFindFirebaseLocation'
         	...amedata\lua.scd\lua\editor\markerbuildconditions.lua(93): in function `?'
         	...n\fa-release-3652\lua\sim\brainconditionsmonitor.lua(254): in function `CheckCondition'
         	...n\fa-release-3652\lua\sim\brainconditionsmonitor.lua(177): in function <...n\fa-release-3652\lua\sim\brainconditionsmonitor.lua:163>
WARNING: Error running lua script: ...faforever\bin\fa-release-3652\lua\ai\aiutilities.lua(558): attempt to call method `GetArmyStartPos' (a nil value)
         stack traceback:
         	...faforever\bin\fa-release-3652\lua\ai\aiutilities.lua(558): in function `AIFindFirebaseLocation'
         	...amedata\lua.scd\lua\editor\markerbuildconditions.lua(93): in function `?'
         	...n\fa-release-3652\lua\sim\brainconditionsmonitor.lua(254): in function `CheckCondition'
         	...n\fa-release-3652\lua\sim\brainconditionsmonitor.lua(177): in function <...n\fa-release-3652\lua\sim\brainconditionsmonitor.lua:163>
WARNING: Error running lua script: ...faforever\bin\fa-release-3652\lua\ai\aiutilities.lua(558): attempt to call method `GetArmyStartPos' (a nil value)
         stack traceback:
         	...faforever\bin\fa-release-3652\lua\ai\aiutilities.lua(558): in function `AIFindFirebaseLocation'
         	...amedata\lua.scd\lua\editor\markerbuildconditions.lua(93): in function `?'
         	...n\fa-release-3652\lua\sim\brainconditionsmonitor.lua(254): in function `CheckCondition'
         	...n\fa-release-3652\lua\sim\brainconditionsmonitor.lua(177): in function <...n\fa-release-3652\lua\sim\braincondition

**Comment by aeoncleanse** [comment]
@speed2CZ One of your coop AI changes may have caused this?

**Comment by speed2CZ** [comment]
don't think so, more like @Crotalus changes

**Comment by Nojoke185** [comment]
This started to be seen in builds around 3-4 days back
Prior to that I didnt see the problems

**Comment by aeoncleanse** [comment]
Should be fixed as 52d7c26d581bb8fa61d7e8d031bacf73b1abc3a5

@Nojoke185 is this good your end?

**Comment by Nojoke185** [comment]
downloaded it again - I am not getting the errors in the F9 log but the issues still remain (nobody shoots each other and I can see enemy buildings being constructed through fog of war)

@aeoncleanse @Crotalus

**Comment by Nojoke185** [comment]
AI cosy in the enemy base: 

![image](https://cloud.githubusercontent.com/assets/16309355/13998513/87e2142e-f12f-11e5-8f44-e9e2e5933545.png)


buildings visible through fog of war:

![image](https://cloud.githubusercontent.com/assets/16309355/13998530/99f9431c-f12f-11e5-951f-83713d981e29.png)

**Comment by Crotalus** [comment]
Ok that's weird, somethign not related to the reveal code though 'cause it happens even when I disable that. Taking a closer look

**Comment by Nojoke185** [comment]
yes it was a sorianAI used

**Comment by Crotalus** [comment]
Yeah, I was rambling. Was a bug with the reveal, without any alliance set at all the default vision between armies seems to be in some weird limbo state.

Try latest version of 3652 now

**Comment by Nojoke185** [comment]
quick test:

units now shoot each other
no sign of buildings being visible when not expected
No F9 log issues

seems ok
