### ISSUE TITLE
ArmyIndex != StartPos leads to wrong scores reported

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#1777]
When a game is started, the host sends the game options for every player to the server. That includes the `army` index, which is just set to the `slotNum` number.

This is incorrect when there are free slots, because the engine always indexes armies starting from 1.

This means that when the game does score reporting based on the aibrain's `GetArmyIndex` function, it will report for the wrong army.

More details here: https://docs.google.com/document/d/1uuDYLmVisrN0GxWSJOWIjSlS1rPtWTtL5fTQL3OPVS4/edit

This almost certainly causes rating bugs.

It is actually hard to link players between lobby and game. The easiest way to associate them for the server is using the connection ID.

So we need to find a way to make sure this stuff is synchronized.

**Comment by aeoncleanse** [comment]
Fixed as of 3672

**Comment by duk3luk3** [comment]
Not fixed! Found a reproducible issue where slot 7 and slot 8 on "Desire" map to army 2 and 1, respectively.

Maybe this is caused by iterating over a hashmap and expecting it to be in order, like the dumbasses we are.

See: http://forums.faforever.com/viewtopic.php?f=3&t=14448

Maybe bug location: https://github.com/FAForever/fa/blob/develop/lua/ui/lobby/lobby.lua#L5959
