### ISSUE TITLE
Exception during gameplay

### ISSUE THREAD

**Issue by norraxx** [FAForever/fa#2668]
```
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x006cbc63
    attempted to read memory at 0x00000000

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /mean 1307.28 /deviation 129.104 /country CZ /init init_faf.lua /numgames 58 /log C:\ProgramData\FAForever\logs\game.uid.8904308.log /nobugreport /savereplay gpgnet://localhost:59054/8904308/dragonite.SCFAreplay /gpgnet 127.0.0.1:59084

Callstack:
	Unknown symbol (address 0x006cbc63)
	Unknown symbol (address 0x006cb8f0)
	Unknown symbol (address 0x1c2e35fb)
	Unknown symbol (address 0x1c2e35fb)

Last 100 lines of log...

debug: Loading module '\000/units/xrb2309/xrb2309_script.lua\000'
debug: Current gametime: 00:34:30
debug: Loading module '\000/units/urs0203/urs0203_script.lua\000'
debug: Loading module '\000/units/urb2304/urb2304_script.lua\000'
debug: Current gametime: 00:35:00
debug: Current gametime: 00:35:30
info: Minimized true
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
info: Minimized false
debug: Loading module '\000/lua/ui/game/zoomslider.lua\000'
debug: Loading module '\000/units/urb5101/urb5101_script.lua\000'
debug: Loading module '\000/units/ual0304/ual0304_script.lua\000'
debug: Current gametime: 00:36:00
debug: Current gametime: 00:36:30
debug: Loading module '\000/units/dalk003/dalk003_script.lua\000'
debug: Current gametime: 00:37:00
debug: Loading module '\000/units/xal0305/xal0305_script.lua\000'
debug: Current gametime: 00:37:30
debug: Loading module '\000/units/urb2204/urb2204_script.lua\000'
info: Minimized true
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
info: Minimized false
debug: Current gametime: 00:38:00
debug: Loading module '\000/units/uaa0310/uaa0310_script.lua\000'
debug: Loading module '\000/units/urb4207/urb4207_script.lua\000'
debug: Loading module '\000/projectiles/aifsonanceshell01/aifsonanceshell01_script.lua\000'
debug: Current gametime: 00:38:30
debug: Loading module '\000/lua/ui/game/confirmunitdestroy.lua\000'
debug: Loading module '\000/lua/ui/game/unittext.lua\000'
info: Minimized true
debug: Loading module '\000/units/urb4201/urb4201_script.lua\000'
debug: Current gametime: 00:39:00
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
info: Minimized false
info: Minimized true
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
info: Minimized false
debug: Current gametime: 00:39:30
debug: Current gametime: 00:40:00
debug: Loading module '\000/units/urb5202/urb5202_script.lua\000'
debug: Current gametime: 00:40:30
debug: Loading module '\000/units/urb2302/urb2302_script.lua\000'
info: Minimized true
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
info: Minimized false
debug: Current gametime: 00:41:00
debug: Current gametime: 00:41:30
debug: Loading module '\000/projectiles/aaserpentine/aaserpentine_script.lua\000'
info: Minimized true
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
info: Minimized false
debug: Loading module '\000/projectiles/adfheavydisruptorcannon01/adfheavydisruptorcannon01_script.lua\000'
debug: Current gametime: 00:42:00
warning: Error running OnRelease script in <deleted object>: ...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua(84): Game object has been destroyed
         stack traceback:
         	[C]: in function `Play'
         	...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua(84): in function <...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua:78>
debug: Loading module '\000/units/urb2101/urb2101_script.lua\000'
debug: Current gametime: 00:42:30
debug: Loading module '\000/projectiles/cdflaserheavy01/cdflaserheavy01_script.lua\000'
debug: Current gametime: 00:43:00
debug: Loading module '\000/projectiles/cifartilleryproton01/cifartilleryproton01_script.lua\000'
debug: Current gametime: 00:43:30
debug: Current gametime: 00:44:00
debug: Current gametime: 00:44:30
debug: Loading module '\000/effects/entities/debrisboneattachlow01/debrisboneattachlow01_script.lua\000'
debug: Loading module '\000/projectiles/cantorpedonanite01/cantorpedonanite01_script.lua\000'
debug: Current gametime: 00:45:00
debug: Loading module '\000/effects/entities/debrismisc010/debrismisc010_script.lua\000'
debug: Loading module '\000/projectiles/cifmissiletactical03/cifmissiletactical03_script.lua\000'
debug: Current gametime: 00:45:30
debug: Loading module '\000/projectiles/adfquantumdisruptor01/adfquantumdisruptor01_script.lua\000'
debug: Current gametime: 00:46:00

```

**Comment by FAETHER** [comment]
Error in AI code from lua. Should be fixed in next binary patch.

**Comment by Uveso** [comment]
This error was caused by my Uveso-AI v45, sorry for that:)
002cbc63 was caused from the function `EngineerMoveWithSafePath`.

It's already fixed in versionUveso-AI v45
http://forums.faforever.com/viewtopic.php?f=88&t=16381
(or mod vault)

**Comment by FAETHER** [comment]
Cool!

**Comment by FAETHER** [comment]
But why its not fixed then? The issue been 2 years ago, and now this is still a thing.

**Comment by FAETHER** [comment]
I'm patching this out in binary anyway. Nothing can be worse than random crash.

**Comment by FAETHER** [comment]
Or there no need now?
