### ISSUE TITLE
sera destro doesn't automaticaly surface when out of facto

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#854]
http://forums.faforever.com/forums/viewtopic.php?f=3&t=10560

**Comment by Sheeo** [comment]
This is starting to become silly.

The code in place for this should be working. It's unclear what would cause `self.originalBuilder` to not be set.

**Comment by speed2CZ** [comment]
@ChrisKitching @Sheeo this issues affects also destroyers that are spawned by script, they still dont surface, so this bug is not fixed yet

**Comment by Sheeo** [comment]
Should be fixed as of 3648.

**Comment by speed2CZ** [comment]
right now, in 3650 its still broken

**Comment by ChrisKitching** [comment]
> right now, in 3650 its still broken

Specifically?

**Comment by speed2CZ** [comment]
destroyers that are spawned by script,(spawned via cheat menu) they still dont surface as I said feew comment above

**Comment by Sheeo** [comment]
Need another issue for this. I consider it rather minor

**Comment by Sheeo** [comment]
if it affects coop or other places it should probably be dealt with there. Or we fix the building animation and have it build in land.

**Comment by ChrisKitching** [comment]
> if it affects coop or other places it should probably be dealt with there.

Destroyers spawned by scripts in coop always belong to the AI, so it seems safe to assume whatever logic the AI uses to decide if it wants its ships surfaced or not will take over and make this a non-problem right away.

**Comment by speed2CZ** [comment]
but AI doesnt really controle it, its script that just sends it on patrol, but you removed the code that surface them when spawned...
So this is an issue
