### ISSUE TITLE
Range overlay reduces FPS by up to 90%

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#94]
Range overlays are a huge performance bottleneck, especially "Selection" and it is enabled for all users as default.

The toll is taken on the GPU so people with fast cards notice less impact but the problem is that if someone is running a low-end gfxcard (like me for the moment), the result is stall / stutter in a network game. The sim and render side isn't decoupled enough :/

For someone wanting to test the impact you can create say, 200 asf and then select those with selection range overlay enabled. As long as you have them selected on screen it will cause a huge fps drop, It is probably the "merge overlay circles" code which is crap.

My suggestion is to remove Selection-overlay as an option in the UI completely and make sure it starts disabled. The only time it should be on is if you select a single unit (which is already the case). It is useless anyway for the multi-unit select case.

I will put up a pull request with some other performance improvements at the same time.

**Comment by aeoncleanse** [comment]
I've had my uncle take a look at this as it appears in game, not the code. He's an expert programmer who specialises in geometric functions for CAD operations, and his jaw dropped when he saw the impact these rings had on FPS. I think it's essential we find out how they are calculated, how the intersect is calculated, and why the hell this FPS drop is happening. On my machine, even selecting 3 ASFs drops my FPS from 60 to 25.

Crucial: Zoom level affects the FPS, so it does appear to be the display aspect rather than the calculation which is causing it.

**Comment by aeoncleanse** [comment]
Since my last post on this, I've upgraded my laptop. The old one had a 560m GPU and an i7 CPU. The new one has an i7 which is slightly faster, but not by much. However, the GPU is a 980m, a SIGNIFICANTLY faster GPU. For me, this issue has completely vanished with the new machine, confirming this is definitely a rendering issue not a CPU side issue.

**Comment by Crotalus** [comment]
Probably fixed by Eximius here:

3cb462d2e7b7b08e57e617b5a3f49d81b3251b9f

**Comment by ChrisKitching** [comment]
Definitely not fixed by Eximius there, but made very slightly less awful.

You really should lurk in Slack more, Crotalus, it's where the low-latency stuff happens.

**Comment by aeoncleanse** [comment]
This is not solved... But is it as far as we can go? Can it be closed?

**Comment by Sheeo** [comment]
The bug remains.

**Comment by HUSSAR-mtrela** [comment]
too bad we cannot fix it now because even with GTX 970 and i7-4930K I see fps drop a lot when selecting a lot of ASFs. Also, there might be something wrong with range rings on SCUs because selecting just a few of them causes fps drop as much as selecting a lot of ASFs... I will investigate it more.

**Comment by Sheeo** [comment]
@HUSSAR-mtrela this cannot possibly be a high priority unless you have found means for changing the render calls.

**Comment by 4z0t** [comment]
Yeah, it is true, they really cause fps drops, I experienced that even having top gpu, the only solution rn is turn off anti aliasing...

**Comment by Garanas** [comment]
This is not fixed, but improved significantly by an engine patch (https://github.com/FAForever/FA-Binary-Patches/commit/d86021174014fc42c2d9d76a79492705f2b52290) and two shader adjustments (a8a1c9befd3d49f7d19e75aa80abeb0ba42ad51d and 6f499ee278f7b5bf0da42f0723b1dc17f9db175c). See also the [forum post](https://forum.faforever.com/topic/4405/game-version-3741-sneak-peaks) with the latest sneak peaks!
